
CREATE DATABASE lamus2 WITH TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'en_US.UTF-8' LC_CTYPE = 'en_US.UTF-8';

-- GIVE ACCESS TO ROLES IN DB - GRANT ALL PRIVILEGES ON DATABASE lamus2 TO webuser; ???

ALTER DATABASE ams2 OWNER TO webuser;
