
ALTER TABLE Workspace DROP CONSTRAINT TopNode;
ALTER TABLE Node DROP CONSTRAINT FKNode812606;
ALTER TABLE NodeLink DROP CONSTRAINT FKNodeLink495772;
DROP TABLE Workspace CASCADE;
DROP TABLE Node CASCADE;
DROP TABLE NodeLink CASCADE;
