
DROP TABLE versions IF EXISTS CASCADE;
DROP VIEW tmp IF EXISTS;
DROP TABLE imdiadmin IF EXISTS;
DROP TABLE corpusstructure IF EXISTS;
DROP TABLE corpusnodes IF EXISTS CASCADE;
DROP VIEW apachedemo IF EXISTS;
DROP TABLE archiveobjects IF EXISTS CASCADE;
DROP SEQUENCE nodeid_seq IF EXISTS;
DROP TABLE accessgroups IF EXISTS CASCADE;