CREATE TABLE workspace (
        workspace_id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
        user_id varchar(30) NOT NULL,
        top_node_id integer NOT NULL,
        start_date timestamp NOT NULL,
        end_date timestamp NOT NULL,
        session_start_date timestamp NOT NULL,
        session_end_date timestamp NOT NULL,
        used_storage_space bigint,
        max_storage_space bigint,
        status varchar(255),
        message varchar(255),
        archive_info varchar(255),
        PRIMARY KEY (workspace_id));

CREATE TABLE node (
        workspace_node_id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
        workspace_id integer NOT NULL,
        archive_node_id integer DEFAULT -1,
        profile_schema_uri varchar(255),
        name varchar(255) NOT NULL,
        title varchar(255),
        workspace_url varchar(255),
        archive_url varchar(255),
        origin_url varchar(255),
        status integer NOT NULL,
        pid varchar(255),
        format varchar(255),
        PRIMARY KEY (workspace_node_id));

CREATE TABLE node_link (
        parent_workspace_node_id integer NOT NULL,
        node_workspace_id integer NOT NULL,
        resource_proxy_id integer NOT NULL);
