
CREATE TABLE accessgroups (
    md5 character varying NOT NULL,
    aclstring character varying NOT NULL,
    PRIMARY KEY (md5)
);


CREATE TABLE archiveobjects (
    nodeid integer GENERATED BY DEFAULT AS IDENTITY (START WITH 0),
    url varchar NOT NULL,
    crawltime timestamp NOT NULL,
    onsite boolean DEFAULT true,
    size bigint,
    checksum varchar,
    filetime timestamp,
    creator varchar,
    owner varchar,
    readrights varchar NOT NULL,
    writerights varchar NOT NULL,
    pid varchar,
    accesslevel integer,
    PRIMARY KEY (nodeid)
);


CREATE TABLE corpusnodes (
    nodeid integer NOT NULL,
    nodetype integer NOT NULL,
    format varchar,
    name varchar,
    title varchar,
    PRIMARY KEY (nodeid)
);


CREATE TABLE corpusstructure (
    nodeid integer NOT NULL,
    canonical boolean DEFAULT false,
    valid boolean DEFAULT true,
    vpath0 integer,
    vpath1 integer,
    vpath2 integer,
    vpath varchar
);


CREATE TABLE imdiadmin (
    name varchar,
    value varchar
);


CREATE TABLE versions (
    nodeid varchar NOT NULL,
    olderversion varchar,
    newerversion varchar,
    retired boolean,
    creation_ts timestamp DEFAULT 'now' NOT NULL,
    PRIMARY KEY (nodeid)
);
